
find_path(MONGODB_INCLUDE_DIR mongo/client/dbclient.h)
find_library(MONGODB_LIBRARY mongoclient)
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MONGODB DEFAULT_MSG MONGODB_LIBRARY  MONGODB_INCLUDE_DIR)

if(MONGODB_FOUND)
	set(MONGODB_LIBRARIES ${MONGODB_LIBRARY})
	set(MONGODB_INCLUDE_DIRS ${MONGODB_INCLUDE_DIR})
endif(MONGODB_FOUND)

mark_as_advanced(MONGODB_LIBRARY MONGODB_INCLUDE_DIR)

